/* Generated By:JavaCC: Do not edit this line. NaturalParserConstants.java */
package uk.ac.warwick.dcs.cobalt.sherlock.freetext;

public interface NaturalParserConstants {

  int EOF = 0;
  int newLine = 1;
  int sentEnd = 2;
  int endBracket = 3;
  int hashLine = 9;
  int number = 10;
  int word = 11;
  int subword = 12;
  int space = 13;
  int others = 14;
  int character_literal = 15;
  int string_literal = 16;

  int DEFAULT = 0;
  int parser = 1;

  String[] tokenImage = {
    "<EOF>",
    "<newLine>",
    "<sentEnd>",
    "<endBracket>",
    "<token of kind 4>",
    "<token of kind 5>",
    "<token of kind 6>",
    "<token of kind 7>",
    "<token of kind 8>",
    "\"#line \"",
    "<number>",
    "<word>",
    "<subword>",
    "<space>",
    "<others>",
    "<character_literal>",
    "<string_literal>",
  };

}
