/* Generated By:JavaCC: Do not edit this line. SentenceParserConstants.java */
package uk.ac.warwick.dcs.cobalt.sherlock.freetext;

public interface SentenceParserConstants {

  int EOF = 0;
  int singleLineComment = 1;
  int newLine = 2;
  int sentEnd = 3;
  int endBracket = 4;
  int formalComment = 10;
  int multiLineComment = 11;
  int endFormalOrMultiLineComment = 12;
  int hashLine = 18;
  int number = 19;
  int word = 20;
  int subword = 21;
  int space = 22;
  int others = 23;
  int character_literal = 24;
  int string_literal = 25;

  int DEFAULT = 0;
  int inSingleLineComment = 1;
  int inFormalOrMultiLineComment = 2;

  String[] tokenImage = {
    "<EOF>",
    "\"//\"",
    "<newLine>",
    "<sentEnd>",
    "<endBracket>",
    "<token of kind 5>",
    "<token of kind 6>",
    "<token of kind 7>",
    "<token of kind 8>",
    "<token of kind 9>",
    "<formalComment>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 13>",
    "<token of kind 14>",
    "<token of kind 15>",
    "<token of kind 16>",
    "<token of kind 17>",
    "\"#line \"",
    "<number>",
    "<word>",
    "<subword>",
    "<space>",
    "<others>",
    "<character_literal>",
    "<string_literal>",
  };

}
