/* Generated By:JavaCC: Do not edit this line. CommentConstants.java */
package uk.ac.warwick.dcs.cobalt.sherlock;

public interface CommentConstants {

  int EOF = 0;
  int singleLineComment = 1;
  int formalComment = 5;
  int multiLineComment = 6;
  int endFormalOrMultiLineComment = 7;
  int newLine = 11;
  int hashLine = 12;
  int number = 13;
  int word = 14;
  int subword = 15;
  int space = 16;
  int others = 17;
  int character_literal = 18;
  int string_literal = 19;

  int DEFAULT = 0;
  int inSingleLineComment = 1;
  int inFormalOrMultiLineComment = 2;

  String[] tokenImage = {
    "<EOF>",
    "\"//\"",
    "<token of kind 2>",
    "<token of kind 3>",
    "<token of kind 4>",
    "<formalComment>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "<token of kind 9>",
    "<token of kind 10>",
    "<newLine>",
    "\"#line \"",
    "<number>",
    "<word>",
    "<subword>",
    "<space>",
    "<others>",
    "<character_literal>",
    "<string_literal>",
  };

}
