/* Generated By:JavaCC: Do not edit this line. cplusplusConstants.java */
package uk.ac.warwick.dcs.cobalt.sherlock;

public interface cplusplusConstants {

  int EOF = 0;
  int newLine = 1;
  int hashLine = 2;
  int singleLineComment = 3;
  int multiLineComment = 4;
  int endAnyMultiLineComment = 7;
  int GOTO = 9;
  int TYPE = 10;
  int AUTO = 11;
  int BREAK = 12;
  int CASE = 13;
  int CATCH = 14;
  int CLASS = 15;
  int CONTINUE = 16;
  int _DEFAULT = 17;
  int DELETE = 18;
  int DO = 19;
  int ELSE = 20;
  int ENUM = 21;
  int EXTERN = 22;
  int FALSE = 23;
  int FINALLY = 24;
  int FLOAT = 25;
  int FOR = 26;
  int FRIEND = 27;
  int IF = 28;
  int IMPLEMENTS = 29;
  int IMPORT = 30;
  int INLINE = 31;
  int INT = 32;
  int INTERFACE = 33;
  int NATIVE = 34;
  int NEW = 35;
  int NULL = 36;
  int PACKAGE = 37;
  int REDECLARED = 38;
  int REGISTER = 39;
  int RETURN = 40;
  int SHORT = 41;
  int SIGNED = 42;
  int SIZEOF = 43;
  int STATIC = 44;
  int STRUCT = 45;
  int SUPER = 46;
  int SWITCH = 47;
  int THIS = 48;
  int THROW = 49;
  int TRUE = 50;
  int TRY = 51;
  int UNION = 52;
  int UNSIGNED = 53;
  int VIRTUAL = 54;
  int WHILE = 55;
  int MODIFIERS = 56;
  int IDENTIFIER = 57;
  int LETTER = 58;
  int DIGIT = 59;
  int INTEGER_LITERAL = 60;
  int DECIMAL_LITERAL = 61;
  int HEX_LITERAL = 62;
  int OCTAL_LITERAL = 63;
  int FLOATING_POINT_LITERAL = 64;
  int EXPONENT = 65;
  int CHARACTER_LITERAL = 66;
  int STRING_LITERAL = 67;
  int LPAREN = 68;
  int RPAREN = 69;
  int LBRACE = 70;
  int RBRACE = 71;
  int LBRACKET = 72;
  int RBRACKET = 73;
  int SEMICOLON = 74;
  int COMMA = 75;
  int DOT = 76;
  int QUESTIONMARK = 77;
  int ELLIPSIS = 78;
  int ASSIGN = 79;
  int GT = 80;
  int LT = 81;
  int BANG = 82;
  int TILDE = 83;
  int SCOPE = 84;
  int COLON = 85;
  int EQ = 86;
  int LE = 87;
  int GE = 88;
  int NE = 89;
  int SC_OR = 90;
  int SC_AND = 91;
  int INCR = 92;
  int DECR = 93;
  int PLUS = 94;
  int MINUS = 95;
  int STAR = 96;
  int SLASH = 97;
  int BIT_AND = 98;
  int BIT_OR = 99;
  int XOR = 100;
  int REM = 101;
  int SHIFT = 102;
  int POINTERTO = 103;
  int DOTSTAR = 104;
  int ARROWSTAR = 105;
  int PLUSASSIGN = 106;
  int MINUSASSIGN = 107;
  int STARASSIGN = 108;
  int SLASHASSIGN = 109;
  int ANDASSIGN = 110;
  int REMASSIGN = 111;
  int SHIFTASSIGN = 112;
  int others = 114;

  int DEFAULT = 0;
  int inSingleLineComment = 1;
  int inAnyMultiLineComment = 2;

  String[] tokenImage = {
    "<EOF>",
    "<newLine>",
    "\"#line \"",
    "\"//\"",
    "\"/*\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"*/\"",
    "<token of kind 8>",
    "\"goto\"",
    "<TYPE>",
    "\"auto\"",
    "\"break\"",
    "\"case\"",
    "\"catch\"",
    "\"class\"",
    "\"continue\"",
    "\"default\"",
    "\"delete\"",
    "\"do\"",
    "\"else\"",
    "\"enum\"",
    "\"extern\"",
    "\"false\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"friend\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"inline\"",
    "\"int\"",
    "\"interface\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"redeclared\"",
    "\"register\"",
    "\"return\"",
    "\"short\"",
    "\"signed\"",
    "\"sizeof\"",
    "\"static\"",
    "\"struct\"",
    "\"super\"",
    "\"switch\"",
    "\"this.\"",
    "\"throw\"",
    "\"true\"",
    "\"try\"",
    "\"union\"",
    "\"unsigned\"",
    "\"virtual\"",
    "\"while\"",
    "<MODIFIERS>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"?\"",
    "\"...\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"::\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "<SHIFT>",
    "\"->\"",
    "\".*\"",
    "\"->*\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "<ANDASSIGN>",
    "\"%=\"",
    "<SHIFTASSIGN>",
    "<token of kind 113>",
    "<others>",
  };

}
