/* Generated By:JavaCC: Do not edit this line. JavaConstants.java */
package uk.ac.warwick.dcs.cobalt.sherlock;

public interface JavaConstants {

  int EOF = 0;
  int newLine = 1;
  int hashLine = 2;
  int singleLineComment = 3;
  int multiLineComment = 4;
  int formalComment = 5;
  int endAnyMultiLineComment = 8;
  int CONST = 10;
  int GOTO = 11;
  int TYPE = 12;
  int BREAK = 13;
  int CASE = 14;
  int CATCH = 15;
  int CLASS = 16;
  int CONTINUE = 17;
  int _DEFAULT = 18;
  int DO = 19;
  int ELSE = 20;
  int FALSE = 21;
  int FINALLY = 22;
  int FLOAT = 23;
  int FOR = 24;
  int IF = 25;
  int IMPLEMENTS = 26;
  int IMPORT = 27;
  int INSTANCEOF = 28;
  int INT = 29;
  int INTERFACE = 30;
  int NATIVE = 31;
  int NEW = 32;
  int NULL = 33;
  int PACKAGE = 34;
  int RETURN = 35;
  int SHORT = 36;
  int SUPER = 37;
  int SWITCH = 38;
  int THIS = 39;
  int THROW = 40;
  int TRUE = 41;
  int TRY = 42;
  int WHILE = 43;
  int ASSERT = 44;
  int MODIFIERS = 45;
  int IDENTIFIER = 46;
  int LETTER = 47;
  int DIGIT = 48;
  int INTEGER_LITERAL = 49;
  int DECIMAL_LITERAL = 50;
  int HEX_LITERAL = 51;
  int OCTAL_LITERAL = 52;
  int FLOATING_POINT_LITERAL = 53;
  int EXPONENT = 54;
  int CHARACTER_LITERAL = 55;
  int STRING_LITERAL = 56;
  int LPAREN = 57;
  int RPAREN = 58;
  int LBRACE = 59;
  int RBRACE = 60;
  int LBRACKET = 61;
  int RBRACKET = 62;
  int SEMICOLON = 63;
  int COMMA = 64;
  int DOT = 65;
  int ASSIGN = 66;
  int GT = 67;
  int LT = 68;
  int BANG = 69;
  int TILDE = 70;
  int HOOK = 71;
  int COLON = 72;
  int EQ = 73;
  int LE = 74;
  int GE = 75;
  int NE = 76;
  int SC_OR = 77;
  int SC_AND = 78;
  int INCR = 79;
  int DECR = 80;
  int PLUS = 81;
  int MINUS = 82;
  int STAR = 83;
  int SLASH = 84;
  int BIT_AND = 85;
  int BIT_OR = 86;
  int XOR = 87;
  int REM = 88;
  int SHIFT = 89;
  int PLUSASSIGN = 90;
  int MINUSASSIGN = 91;
  int STARASSIGN = 92;
  int SLASHASSIGN = 93;
  int ANDASSIGN = 94;
  int REMASSIGN = 95;
  int SHIFTASSIGN = 96;
  int others = 98;

  int DEFAULT = 0;
  int inSingleLineComment = 1;
  int inAnyMultiLineComment = 2;

  String[] tokenImage = {
    "<EOF>",
    "<newLine>",
    "\"#line \"",
    "\"//\"",
    "\"/*\"",
    "<formalComment>",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"*/\"",
    "<token of kind 9>",
    "\"const\"",
    "\"goto\"",
    "<TYPE>",
    "\"break\"",
    "\"case\"",
    "\"catch\"",
    "\"class\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"else\"",
    "\"false\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"return\"",
    "\"short\"",
    "\"super\"",
    "\"switch\"",
    "\"this.\"",
    "\"throw\"",
    "\"true\"",
    "\"try\"",
    "\"while\"",
    "\"assert\"",
    "<MODIFIERS>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "<SHIFT>",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "<ANDASSIGN>",
    "\"%=\"",
    "<SHIFTASSIGN>",
    "<token of kind 97>",
    "<others>",
  };

}
