/* Generated By:JavaCC: Do not edit this line. NoCommentConstants.java */
package uk.ac.warwick.dcs.cobalt.sherlock;

public interface NoCommentConstants {

  int EOF = 0;
  int singleLineComment = 1;
  int anyMultiLineComment = 2;
  int endAnyMultiLineComment = 5;
  int newLine = 7;
  int hashLine = 8;
  int number = 9;
  int others = 10;

  int DEFAULT = 0;
  int inSingleLineComment = 1;
  int inAnyMultiLineComment = 2;

  String[] tokenImage = {
    "<EOF>",
    "\"//\"",
    "\"/*\"",
    "<token of kind 3>",
    "<token of kind 4>",
    "\"*/\"",
    "<token of kind 6>",
    "<newLine>",
    "\"#line \"",
    "<number>",
    "<others>",
  };

}
