/* Generated By:JavaCC: Do not edit this line. NormaliserTokenManager.java */
package uk.ac.warwick.dcs.cobalt.sherlock;
import java.io.*;
import java.util.Date;

public class NormaliserTokenManager implements NormaliserConstants
{
  public static  java.io.PrintStream debugStream = System.out;
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 10;
            return 3;
         }
         if ((active0 & 0x10L) != 0L)
            return 38;
         if ((active0 & 0x800000L) != 0L)
         {
            jjmatchedKind = 10;
            return 37;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private final int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private final int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static private final int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 10:
         return jjStopAtPos(0, 17);
      case 34:
         return jjStopAtPos(0, 18);
      case 35:
         return jjMoveStringLiteralDfa1_0(0x4000L);
      case 39:
         return jjStopAtPos(0, 19);
      case 40:
         return jjStartNfaWithStates_0(0, 4, 38);
      case 41:
         return jjStopAtPos(0, 5);
      case 42:
         return jjMoveStringLiteralDfa1_0(0x2000000L);
      case 47:
         return jjMoveStringLiteralDfa1_0(0x800000L);
      case 59:
         return jjStopAtPos(0, 7);
      case 92:
         return jjMoveStringLiteralDfa1_0(0x300000L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private final int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 34:
         if ((active0 & 0x100000L) != 0L)
            return jjStopAtPos(1, 20);
         break;
      case 39:
         if ((active0 & 0x200000L) != 0L)
            return jjStopAtPos(1, 21);
         break;
      case 47:
         if ((active0 & 0x800000L) != 0L)
            return jjStopAtPos(1, 23);
         else if ((active0 & 0x2000000L) != 0L)
            return jjStopAtPos(1, 25);
         break;
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private final int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
static private final int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
static private final int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
static private final int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 32:
         if ((active0 & 0x4000L) != 0L)
            return jjStopAtPos(5, 14);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
static private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
static private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
static private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 38;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 37:
                  if (curChar == 42)
                     jjCheckNAdd(36);
                  else if (curChar == 61)
                  {
                     if (kind > 10)
                        kind = 10;
                  }
                  if (curChar == 42)
                  {
                     if (kind > 24)
                        kind = 24;
                  }
                  break;
               case 38:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 10)
                     jjCheckNAddTwoStates(15, 11);
                  else if (curChar == 32)
                     jjCheckNAddTwoStates(10, 11);
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 15)
                        kind = 15;
                     jjCheckNAdd(16);
                  }
                  else if ((0xf400ac6000000000L & l) != 0L)
                  {
                     if (kind > 10)
                        kind = 10;
                  }
                  else if (curChar == 32)
                  {
                     if (kind > 16)
                        kind = 16;
                     jjCheckNAdd(17);
                  }
                  else if (curChar == 40)
                     jjCheckNAddStates(4, 6);
                  else if (curChar == 33)
                     jjCheckNAdd(3);
                  if (curChar == 47)
                     jjCheckNAddStates(7, 9);
                  else if (curChar == 45)
                     jjCheckNAddTwoStates(34, 3);
                  else if (curChar == 43)
                     jjCheckNAddTwoStates(32, 3);
                  else if (curChar == 60)
                     jjCheckNAddStates(10, 12);
                  else if (curChar == 38)
                     jjCheckNAddTwoStates(27, 3);
                  else if (curChar == 62)
                     jjCheckNAddStates(13, 17);
                  else if (curChar == 37)
                     jjCheckNAdd(3);
                  else if (curChar == 42)
                     jjCheckNAdd(3);
                  else if (curChar == 61)
                     jjCheckNAdd(3);
                  else if (curChar == 33)
                  {
                     if (kind > 9)
                        kind = 9;
                  }
                  break;
               case 1:
                  if (curChar == 33 && kind > 9)
                     kind = 9;
                  break;
               case 2:
                  if ((0xf400ac6000000000L & l) != 0L && kind > 10)
                     kind = 10;
                  break;
               case 3:
                  if (curChar == 61 && kind > 10)
                     kind = 10;
                  break;
               case 4:
                  if (curChar == 61)
                     jjCheckNAdd(3);
                  break;
               case 5:
                  if (curChar == 33)
                     jjCheckNAdd(3);
                  break;
               case 6:
                  if (curChar == 42)
                     jjCheckNAdd(3);
                  break;
               case 7:
                  if (curChar == 37)
                     jjCheckNAdd(3);
                  break;
               case 9:
                  if (curChar == 40)
                     jjCheckNAddStates(4, 6);
                  break;
               case 10:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(10, 11);
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  break;
               case 12:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(12, 13);
                  break;
               case 13:
                  if (curChar == 41)
                     kind = 11;
                  break;
               case 14:
                  if (curChar == 10)
                     jjCheckNAddTwoStates(14, 13);
                  break;
               case 15:
                  if (curChar == 10)
                     jjCheckNAddTwoStates(15, 11);
                  break;
               case 16:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 15)
                     kind = 15;
                  jjCheckNAdd(16);
                  break;
               case 17:
                  if (curChar != 32)
                     break;
                  if (kind > 16)
                     kind = 16;
                  jjCheckNAdd(17);
                  break;
               case 18:
                  if (curChar == 62)
                     jjCheckNAddStates(13, 17);
                  break;
               case 19:
                  if (curChar == 62 && kind > 10)
                     kind = 10;
                  break;
               case 20:
                  if (curChar == 62)
                     jjCheckNAdd(19);
                  break;
               case 21:
               case 22:
                  if (curChar == 62)
                     jjCheckNAdd(3);
                  break;
               case 23:
                  if (curChar == 62)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 26:
                  if (curChar == 38)
                     jjCheckNAddTwoStates(27, 3);
                  break;
               case 27:
                  if (curChar == 38 && kind > 10)
                     kind = 10;
                  break;
               case 28:
                  if (curChar == 60)
                     jjCheckNAddStates(10, 12);
                  break;
               case 29:
                  if (curChar == 60 && kind > 10)
                     kind = 10;
                  break;
               case 30:
                  if (curChar == 60)
                     jjCheckNAdd(3);
                  break;
               case 31:
                  if (curChar == 43)
                     jjCheckNAddTwoStates(32, 3);
                  break;
               case 32:
                  if (curChar == 43 && kind > 8)
                     kind = 8;
                  break;
               case 33:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(34, 3);
                  break;
               case 34:
                  if (curChar == 45 && kind > 8)
                     kind = 8;
                  break;
               case 35:
                  if (curChar == 47)
                     jjCheckNAddStates(7, 9);
                  break;
               case 36:
                  if (curChar == 42 && kind > 24)
                     kind = 24;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 38:
               case 11:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  break;
               case 0:
                  if ((0x1000000040000000L & l) != 0L)
                  {
                     if (kind > 10)
                        kind = 10;
                  }
                  else if ((0x2800000000000000L & l) != 0L)
                  {
                     if (kind > 6)
                        kind = 6;
                  }
                  else if (curChar == 126)
                  {
                     if (kind > 9)
                        kind = 9;
                  }
                  if (curChar == 124)
                     jjCheckNAddTwoStates(25, 3);
                  else if (curChar == 94)
                     jjCheckNAdd(3);
                  break;
               case 1:
                  if (curChar == 126)
                     kind = 9;
                  break;
               case 2:
                  if ((0x1000000040000000L & l) != 0L && kind > 10)
                     kind = 10;
                  break;
               case 8:
                  if (curChar == 94)
                     jjCheckNAdd(3);
                  break;
               case 24:
                  if (curChar == 124)
                     jjCheckNAddTwoStates(25, 3);
                  break;
               case 25:
                  if (curChar == 124 && kind > 10)
                     kind = 10;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 38 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   11, 12, 14, 13, 10, 15, 11, 3, 36, 37, 29, 3, 30, 19, 20, 3, 
   21, 23, 
};
public static final String[] jjstrLiteralImages = {
"", null, null, null, "\50", "\51", null, "\73", null, null, null, null, null, 
null, "\43\154\151\156\145\40", null, null, "\12", "\42", "\47", "\134\42", 
"\134\47", null, "\57\57", null, "\52\57", };
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0x3ffcff1L, 
};
static final long[] jjtoSkip = {
   0xeL, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[38];
static private final int[] jjstateSet = new int[76];
static protected char curChar;
public NormaliserTokenManager(SimpleCharStream stream)
{
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}
public NormaliserTokenManager(SimpleCharStream stream, int lexState)
{
   this(stream);
   SwitchTo(lexState);
}
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 38; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

public static Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 13 && (0x3200L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedPos == 0 && jjmatchedKind > 22)
   {
      jjmatchedKind = 22;
   }
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

}
