/* Generated By:JavaCC: Do not edit this line. NormaliserConstants.java */
package uk.ac.warwick.dcs.cobalt.sherlock;

public interface NormaliserConstants {

  int EOF = 0;
  int OPEN_BRACKET = 4;
  int CLOSE_BRACKET = 5;
  int BRACES = 6;
  int SEMICOLON = 7;
  int INC_OPT = 8;
  int NOT_OPT = 9;
  int OPERATOR = 10;
  int CAST = 11;
  int LITERAL = 12;
  int GAP = 13;
  int LINENO = 14;
  int NUMBER = 15;
  int SPACE = 16;
  int NEWLINE = 17;
  int DQUOTE = 18;
  int SQUOTE = 19;
  int DQUOTE_ESCAPE = 20;
  int SQUOTE_ESCAPE = 21;
  int OTHER = 22;
  int SINGLECOMMENT = 23;
  int MULTICOMMENTSTART = 24;
  int MULTICOMMENTEND = 25;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"(\"",
    "\")\"",
    "<BRACES>",
    "\";\"",
    "<INC_OPT>",
    "<NOT_OPT>",
    "<OPERATOR>",
    "<CAST>",
    "<LITERAL>",
    "<GAP>",
    "\"#line \"",
    "<NUMBER>",
    "<SPACE>",
    "\"\\n\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"\\\\\\\"\"",
    "\"\\\\\\\'\"",
    "<OTHER>",
    "\"//\"",
    "<MULTICOMMENTSTART>",
    "\"*/\"",
  };

}
