/* Generated By:JavaCC: Do not edit this line. NoWhiteConstants.java */
package uk.ac.warwick.dcs.cobalt.sherlock;

public interface NoWhiteConstants {

  int EOF = 0;
  int hashLine = 1;
  int number = 2;
  int newLine = 3;
  int space = 4;
  int tab = 5;
  int others = 6;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"#line \"",
    "<number>",
    "<newLine>",
    "\" \"",
    "\"\\t\"",
    "<others>",
  };

}
